from pygame.locals import USEREVENT

"""Game constants to tweak portions of the game"""

DISP_WIDTH = 1024
DISP_HEIGHT = 620

LOCAL_MP = True

SHIP_ACCELERATION = 0.15
SHIP_CONTROL_PRESET = 0 # See ship_controls.py

COLLISION_ALGORITHM_EXPERIMENTAL = 0
COLLISION_ACCURACY = 2
COLLISION_DAMPING = .9

COLLISION_UNSTUCK_EVENT_ID = USEREVENT + 1
COLLISION_UNSTUCK_AGGRESSION = 30

COLLISION_STUCK_THRESHOLD = 35